InterviewTask.WebApp/Models/TestResult.cs
namespace InterviewTask.WebApp.Models
{
    public class TestResult
    {
        public bool IsValid { get; set; } = true;
        public string Message { get; set; }
    }
}

InterviewTask.WebApp/Controllers/CrawlerController.cs
using InterviewTask.Logic.Services;
using InterviewTask.Logic.Validators;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace InterviewTask.WebApp.Controllers
{
    public class CrawlerController : Controller
    {
        private readonly WebApplication _webApp;
        private readonly LinkValidator _linkValidator;

        public CrawlerController(WebApplication webApp, LinkValidator linkValidator)
        {
            _webApp = webApp;
            _linkValidator = linkValidator;
        }

        [HttpPost]
        public async Task<IActionResult> Input(Uri inputLink)
        {
            try
            {
                await _linkValidator.CheckLinkAsync(inputLink);
            }
            catch (Exception ex)
            {
                return RedirectToAction("GetTest", "Result", new { ex.Message });
            }

            await _webApp.StartAsync(inputLink);
            return RedirectToAction("GetTest", "Result", new { message = "Parsing completed successfully" });
        }
    }
}

InterviewTask.WebApp/Controllers/ResultController.cs
using InterviewTask.Logic.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace InterviewTask.WebApp.Controllers
{
    public class ResultController : Controller
    {
        private readonly DatabaseService _databaseOperation;

        public ResultController(DatabaseService databaseOperation)
        {
            _databaseOperation = databaseOperation;
        }

        [HttpGet]
        public async Task<IActionResult> GetTest(int page = 1, int pageSize = 3, string message = null)
        {
            var resultTest = await _databaseOperation.GetPageTestsAsync(page, pageSize);

            ViewData["message"] = message;

            return View(resultTest);
        }

        [HttpGet]
        public IActionResult GetCrawlingResults(int id)
        {
            var linksResult = _databaseOperation.GetListAllLinks(id);

            return View(linksResult);
        }
    }
}

InterviewTask.WebApp/Views/Crawler/Input.cshtml
@{
    ViewData["Title"] = "View";
}

<h1 class="text-center | display-4">
    Welcome
</h1>

<div>
    <form method="post" class="form-group">
        <h3>
            <input size="50" type="url" name="inputLink" placeholder="https:/example.com/" />
            <input asp-controller="Crawler" asp-action="Input" class="table-light" type="submit" value="Parsing" />
        </h3>
    </form>
</div>

InterviewTask.WebApp/Views/Result/GetCrawlingResults.cshtml
@model IEnumerable<Result>
@{ 
    ViewData["Title"] = "Info";
}

<div style="padding: 50px 0px 100px 0px;">
    <h5>Urls FOUNDED IN SITEMAP but not founded after crawling a web site:</h5>
    @await Html.PartialAsync("PartialView/LinksOutput", Model.Where(s => !s.IsLinkFromHtml && s.IsLinkFromSitemap))
</div>

<div style="padding: 0px 0px 100px 0px;">
    <h5>Urls FOUNDED BY CRAWLING THE WEBSITE but not in sitemap:</h5>
    @await Html.PartialAsync("PartialView/LinksOutput", Model.Where(s => s.IsLinkFromHtml && !s.IsLinkFromSitemap))
</div>

<div style="padding: 0px 0px 100px 0px;" class="table-responsive">
    <h5>Timing website(ms):</h5>
    @await Html.PartialAsync("PartialView/LinksWithResponseTimeOutput", Model.OrderBy(r => r.ResponseTime))
</div>

<div>
    <h4>Urls(html documents) found after crawling a website: @Model.Where(l => (l.IsLinkFromHtml)).Count()</h4>
    <h4>Urls found in sitemap: @Model.Where(l => (l.IsLinkFromSitemap)).Count()</h4>
</div>

InterviewTask.WebApp/Views/Result/GetTest.cshtml
@model ResultPagination<InterviewTask.Logic.Models.TestModel>
@{
    ViewData["Title"] = "TestInfo";
}

@await Html.PartialAsync("/Views/Crawler/Input.cshtml")

@if (ViewData["message"] != null)
{
    <ul>
        <li>
            @ViewData["message"]
        </li>
    </ul>
}

<div class="table-responsive" style="padding: 120px 0px 100px 0px;">
    <table border="1" class="bg-light | table">
        <thead>
            <tr class="text-center">
                <th>Base url</th>
                <th>Parsing date</th>
                <th>List all links</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.List)
            {
                <tr>
                    <td width=300>@item.BaseUrl</td>
                    <td width=200>@item.ParsingDate</td>
                    <td class="text-center" width=150>
                        @Html.ActionLink("Details", "GetCrawlingResults", "Result", new { id = item.Id }, new { @class = "btn | btn-outline-dark" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="custom-control">
        <h4>
            @if (Model.CurrentPage > 1)
            {
                @Html.ActionLink("prev", "GetTest", "Result", new { page = Model.CurrentPage - 1 }, new { @class = "btn | btn-outline-secondary" })
            }

            @for (int i = 1; i <= Model.TotalPage; i++)
            {
                if (i == Model.CurrentPage)
                {
                    @Html.ActionLink(i.ToString(), "GetTest", "Result", new { page = i }, new { @class = "btn | btn-outline-success" })
                }
                else
                {
                    @Html.ActionLink(i.ToString(), "GetTest", "Result", new { page = i }, new { @class = "btn | btn-outline-secondary" })
                }
            }

            @if (Model.CurrentPage < Model.TotalPage)
            {
                @Html.ActionLink("next", "GetTest", "Result", new { page = Model.CurrentPage + 1 }, new { @class = "btn | btn-outline-secondary" })
            }

        </h4>
    </div>
</div>

InterviewTask.WebApp/Views/Result/PartialView/LinksOutput.cshtml
@model IEnumerable<Result>

<div class="table-responsive">
    <table border="1" class="bg-light | table">
        <thead>
            <tr class="text-center">
                <th>Link</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model)
                {
                    <tr>
                        <td width=1200>@item.Url</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

InterviewTask.WebApp/Views/Result/PartialView/LinksWithResponseTimeOutput.cshtml
@model IEnumerable<InterviewTask.Logic.Models.Result>

<div class="table-responsive">
    <table border="1" class="bg-light | table">
        <thead>
            <tr class="text-center">
                <th>№</th>
                <th>Link</th>
                <th>Response time</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
                foreach (var item in Model)
                {
                    <tr>
                        <td width=50 class="text-center">@(i++)</td>
                        <td width=1200>@item.Url</td>
                        <td width=70 class="text-center">@item.ResponseTime</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

InterviewTask.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InterviewTask.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @Html.ActionLink("InterviewTask.WebApp", "GetTest", "Result", null, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @Html.ActionLink("Crawling", "GetTest", "Result", null, new { @class = "nav-link text-dark" })
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>